CREATE SEQUENCE ACCOUNT_BALANCE_SEQ START WITH 1;
CREATE SEQUENCE ACCOUNT_ENTRY_SEQ START WITH 1;

CREATE TABLE ACCOUNT_BALANCE(
    ID BIGINT NOT NULL,
    CREATION_TIMESTAMP TIMESTAMP NOT NULL,
    BALANCE BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    CLOSED BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ACCOUNT_ENTRY(
    ID BIGINT NOT NULL,
    CREATION_TIMESTAMP TIMESTAMP NOT NULL,
    AMOUNT BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    IS_ERROR BOOLEAN NOT NULL,
    PROCESSING_TIMESTAMP TIMESTAMP,
    PRIMARY KEY(ID)
);
